// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/constraint;
import ballerina/http;

listener http:Listener ep0 = new (9090);

service http:InterceptableService / on ep0 {
    public function createInterceptors() returns AssertionInterceptor => new;

    # The caller's todos
    #
    # + status - Filter by open or done
    # + return - returns can be any of following types
    # http:Ok (A page of the caller's todos)
    # http:Unauthorized (Not signed in)
    resource function get me/todos(http:RequestContext ctx, "open"|"done"? status, int 'limit = 20, int offset = 0)
            returns inline_response_200|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller !is GatewayCaller {
            return <ErrorUnauthorized>{body: {code: 401, message: "not signed in"}};
        }
        int pageLimit = 'limit > 100 ? 100 : 'limit;
        [int, TodoRow[]] result = check listTodos(caller.userId, status, pageLimit, offset);
        int total = result[0];
        TodoRow[] rows = result[1];
        Todo[] data = from TodoRow row in rows select toTodo(row);
        return {count: total, data: data};
    }

    # Create a new todo for the caller
    #
    # + return - returns can be any of following types
    # http:Created (The created todo)
    # http:BadRequest (Invalid todo)
    # http:Unauthorized (Not signed in)
    resource function post me/todos(http:RequestContext ctx, @http:Payload NewTodo payload)
            returns Todo|ErrorBadRequest|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller !is GatewayCaller {
            return <ErrorUnauthorized>{body: {code: 401, message: "not signed in"}};
        }
        TodoRow row = check createTodo(caller.userId, payload.description);
        return toTodo(row);
    }

    # Mark one of the caller's todos as done
    #
    # + return - returns can be any of following types
    # http:Ok (The updated todo)
    # http:NotFound (No such todo for the caller)
    # http:Unauthorized (Not signed in)
    resource function post me/todos/[string todoId]/complete(http:RequestContext ctx)
            returns TodoOk|ErrorNotFound|ErrorUnauthorized|error {
        GatewayCaller|http:Unauthorized caller = requireGatewayCaller(ctx);
        if caller !is GatewayCaller {
            return <ErrorUnauthorized>{body: {code: 401, message: "not signed in"}};
        }
        TodoRow? row = check completeTodo(caller.userId, todoId);
        if row is () {
            return <ErrorNotFound>{body: {code: 404, message: "no such todo for the caller"}};
        }
        return <TodoOk>{body: toTodo(row)};
    }
}

public type TodoOk record {|
    *http:Ok;
    Todo body;
|};

public type Todo record {
    string id;
    string description;
    boolean done;
    string createdAt;
    string? completedAt?;
};

public type NewTodo record {
    @constraint:String {maxLength: 500, minLength: 1}
    string description;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type inline_response_200 record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Todo[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
